# Generated by Django 4.2.30 on 2026-08-26 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('APPROVAL_NEEDED', 'Approval needed'), ('GOAL_REACHED', 'Goal reached'), ('DEPOSIT_RECEIVED', 'Deposit received'), ('WITHDRAWAL_COMPLETED', 'Withdrawal completed'), ('EMERGENCY_REJECTED', 'Emergency rejected'), ('GROUP_INVITE', 'Group invite'), ('DEADLINE_NEAR', 'Deadline approaching')], max_length=32)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_c4e471_idx')],
            },
        ),
    ]
