# Generated by Django 4.2.30 on 2026-10-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('APPROVAL_NEEDED', 'Approval needed'), ('GOAL_REACHED', 'Goal reached'), ('DEPOSIT_RECEIVED', 'Deposit received'), ('WITHDRAWAL_COMPLETED', 'Withdrawal completed'), ('EMERGENCY_REJECTED', 'Emergency rejected'), ('GROUP_INVITE', 'Group invite'), ('DEADLINE_NEAR', 'Deadline approaching'), ('LOCKER_MATURED', 'Savings locker matured'), ('LOCKER_PENALTY_APPLIED', 'Early-withdrawal penalty applied'), ('KYC_UPDATE', 'KYC status update')], max_length=32),
        ),
    ]
