# Generated by Django 4.2.30 on 2026-08-26 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GROUP', 'Group')], max_length=12)),
                ('goal_name', models.CharField(max_length=150)),
                ('target_amount_paise', models.BigIntegerField()),
                ('balance_paise', models.BigIntegerField(default=0)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('UNLOCKED', 'Unlocked'), ('WITHDRAWN', 'Withdrawn'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='savings_account', to='savings.savingsgroup')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='savings_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'savings_accounts',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CREATOR', 'Creator'), ('MEMBER', 'Member')], default='MEMBER', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='savings.savingsgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_members',
            },
        ),
        migrations.AddConstraint(
            model_name='savingsaccount',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('group__isnull', True), ('owner_type', 'INDIVIDUAL'), ('user__isnull', False)), models.Q(('group__isnull', False), ('owner_type', 'GROUP'), ('user__isnull', True)), _connector='OR'), name='savings_owner_exactly_one'),
        ),
        migrations.AddConstraint(
            model_name='savingsaccount',
            constraint=models.CheckConstraint(check=models.Q(('target_amount_paise__gt', 0)), name='savings_target_positive'),
        ),
        migrations.AddConstraint(
            model_name='savingsaccount',
            constraint=models.CheckConstraint(check=models.Q(('balance_paise__gte', 0)), name='savings_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='groupmember',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='uniq_group_member'),
        ),
    ]
