# Generated by Django 4.2.30 on 2026-10-06 16:09
"""
Term lockers are retired. Before their tables go, any locker that still holds
money is paid back IN FULL (principal + every paisa of accrued interest, no
early-closure penalty - closing it was our decision, not the user's) to the
owner's wallet, with a statement row so the wallet ledger still replays.
"""
import uuid

from django.db import migrations
from django.utils import timezone


def refund_open_lockers(apps, schema_editor):
    Locker = apps.get_model("savings", "SavingsLocker")
    User = apps.get_model("accounts", "User")
    WalletTransaction = apps.get_model("payments", "WalletTransaction")

    for locker in Locker.objects.filter(status__in=["ACTIVE", "MATURED"]):
        payout = locker.principal_paise + locker.accrued_interest_paise
        user = User.objects.select_for_update().get(pk=locker.user_id)
        user.digital_wallet_balance_paise += payout
        user.save(update_fields=["digital_wallet_balance_paise"])
        WalletTransaction.objects.create(
            user=user,
            kind="FROM_LOCKER",
            amount_paise=payout,
            balance_after_paise=user.digital_wallet_balance_paise,
            reference=f"LCP-{uuid.uuid4().hex[:10].upper()}",
            description=f'Term locker "{locker.goal_name}" closed and refunded in full',
        )
        locker.status = "WITHDRAWN"
        locker.closed_at = timezone.now()
        locker.save(update_fields=["status", "closed_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_savings_lockers'),
        ('payments', '0002_wallet_transactions'),
        ('accounts', '0004_biometrics'),
    ]

    operations = [
        migrations.RunPython(refund_open_lockers, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='lockerledgerentry',
            name='locker',
        ),
        migrations.RemoveField(
            model_name='savingslocker',
            name='user',
        ),
        migrations.DeleteModel(
            name='LockerAuditLog',
        ),
        migrations.DeleteModel(
            name='LockerLedgerEntry',
        ),
        migrations.DeleteModel(
            name='SavingsLocker',
        ),
    ]
