# Generated by Django 4.2.30 on 2026-08-26 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('USER_REGISTERED', 'User registered'), ('LOGIN_SUCCESS', 'Login success'), ('LOGIN_FAILED', 'Login failed'), ('DEVICE_REGISTERED', 'Device registered'), ('DEVICE_REVOKED', 'Device revoked'), ('GOAL_CREATED', 'Goal created'), ('DEPOSIT_MADE', 'Deposit made'), ('WITHDRAWAL_MADE', 'Withdrawal made'), ('EMERGENCY_RAISED', 'Emergency raised'), ('EMERGENCY_APPROVED', 'Emergency approved'), ('EMERGENCY_REJECTED', 'Emergency rejected'), ('EMERGENCY_RELEASED', 'Emergency funds released'), ('OTP_VERIFIED', 'OTP verified'), ('BIOMETRIC_VERIFIED', 'Biometric verified'), ('BIOMETRIC_FAILED', 'Biometric failed')], max_length=32)),
                ('entity_type', models.CharField(blank=True, max_length=60)),
                ('entity_id', models.BigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.device')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', '-created_at'], name='audit_logs_actor_i_3b0e80_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_logs_entity__d4c2e5_idx'), models.Index(fields=['action', '-created_at'], name='audit_logs_action_bcaa71_idx')],
            },
        ),
    ]
