# Generated by Django 4.2.30 on 2026-10-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('USER_REGISTERED', 'User registered'), ('LOGIN_SUCCESS', 'Login success'), ('LOGIN_FAILED', 'Login failed'), ('DEVICE_REGISTERED', 'Device registered'), ('DEVICE_REVOKED', 'Device revoked'), ('GOAL_CREATED', 'Goal created'), ('DEPOSIT_MADE', 'Deposit made'), ('WITHDRAWAL_MADE', 'Withdrawal made'), ('EMERGENCY_RAISED', 'Emergency raised'), ('EMERGENCY_APPROVED', 'Emergency approved'), ('EMERGENCY_REJECTED', 'Emergency rejected'), ('EMERGENCY_RELEASED', 'Emergency funds released'), ('OTP_VERIFIED', 'OTP verified'), ('BIOMETRIC_VERIFIED', 'Biometric verified'), ('BIOMETRIC_FAILED', 'Biometric failed'), ('LOCKER_CREATED', 'Savings locker created'), ('LOCKER_PREVIEW', 'Withdrawal preview requested'), ('LOCKER_WITHDRAWN', 'Locker withdrawn'), ('LOCKER_PENALTY', 'Early-withdrawal penalty assessed'), ('KYC_SUBMITTED', 'KYC submitted'), ('KYC_APPROVED', 'KYC approved'), ('KYC_REJECTED', 'KYC rejected'), ('KYC_DOCUMENT_VIEWED', 'KYC document viewed by staff'), ('BANK_LINKED', 'Bank account linked'), ('WALLET_TOPUP', 'Wallet topped up via gateway')], max_length=32),
        ),
    ]
