# Generated by Django 4.2.30 on 2026-10-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='digital_wallet_balance_paise',
            field=models.BigIntegerField(default=0),
        ),
    ]
