# Generated by Django 4.2.30 on 2026-10-06 16:12

import apps.accounts.models
from django.conf import settings
from django.db import migrations, models


def drop_sandbox_bank_accounts(apps, schema_editor):
    """Signup used to auto-create a fake HDFC account; real linking replaces it."""
    LinkedBankAccount = apps.get_model("accounts", "LinkedBankAccount")
    LinkedBankAccount.objects.filter(upi_id__endswith="@digibank", account_fingerprint="").delete()
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_biometrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedbankaccount',
            name='account_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='linkedbankaccount',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='linkedbankaccount',
            name='account_type',
            field=models.CharField(choices=[('SAVINGS', 'Savings'), ('CURRENT', 'Current')], default='SAVINGS', max_length=10),
        ),
        migrations.AddField(
            model_name='linkedbankaccount',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='linkedbankaccount',
            name='branch',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='KycProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Exactly as printed on the PAN card', max_length=150)),
                ('date_of_birth', models.DateField()),
                ('pan_encrypted', models.TextField()),
                ('pan_last4', models.CharField(max_length=4)),
                ('aadhaar_last4', models.CharField(blank=True, max_length=4)),
                ('occupation', models.CharField(choices=[('STUDENT', 'Student'), ('SALARIED', 'Salaried'), ('SELF_EMPLOYED', 'Self-employed'), ('HOMEMAKER', 'Homemaker'), ('RETIRED', 'Retired'), ('OTHER', 'Other')], max_length=16)),
                ('address_line1', models.CharField(max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('pincode', models.CharField(max_length=6)),
                ('pan_document', models.FileField(upload_to=apps.accounts.models._kyc_upload_path)),
                ('address_proof_type', models.CharField(choices=[('AADHAAR', 'Aadhaar card'), ('PASSPORT', 'Passport'), ('VOTER_ID', 'Voter ID'), ('DRIVING_LICENCE', 'Driving licence')], max_length=16)),
                ('address_document', models.FileField(upload_to=apps.accounts.models._kyc_upload_path)),
                ('selfie', models.FileField(upload_to=apps.accounts.models._kyc_upload_path)),
                ('auto_checks', models.JSONField(blank=True, default=dict)),
                ('consent_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField()),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=300)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kyc_profiles',
            },
        ),
        migrations.RunPython(drop_sandbox_bank_accounts, migrations.RunPython.noop),
    ]
