# Generated by Django 4.2.30 on 2026-08-26 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('EMERGENCY_APPROVAL', 'Emergency approval'), ('WITHDRAWAL', 'Withdrawal'), ('LOGIN', 'Login'), ('DEVICE_REGISTRATION', 'Device registration')], max_length=24)),
                ('otp_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'otp_verifications',
            },
        ),
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paise', models.BigIntegerField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('COMPLETED', 'Completed')], default='PENDING', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emergency_requests', to=settings.AUTH_USER_MODEL)),
                ('savings_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emergency_requests', to='savings.savingsaccount')),
            ],
            options={
                'db_table': 'emergency_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=8)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('otp_verification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='emergency.otpverification')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='emergency.emergencyrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emergency_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emergency_approvals',
            },
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['user', 'purpose', '-created_at'], name='otp_verific_user_id_aa8117_idx'),
        ),
        migrations.AddConstraint(
            model_name='emergencyrequest',
            constraint=models.CheckConstraint(check=models.Q(('amount_paise__gt', 0)), name='emergency_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='emergencyrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('savings_account',), name='uniq_pending_emergency_per_account'),
        ),
        migrations.AddConstraint(
            model_name='emergencyapproval',
            constraint=models.UniqueConstraint(fields=('request', 'user'), name='uniq_approval_per_member'),
        ),
    ]
