# Generated by Django 4.2.30 on 2026-09-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('EMERGENCY_APPROVAL', 'Emergency approval'), ('WITHDRAWAL', 'Withdrawal'), ('LOGIN', 'Login'), ('DEVICE_REGISTRATION', 'Device registration'), ('SIGNUP_VERIFICATION', 'Signup verification'), ('PASSWORD_RESET', 'Password reset')], max_length=24),
        ),
    ]
