# Generated by Django 4.2.30 on 2026-08-26 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emergency', '0001_initial'),
        ('savings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal')], max_length=12)),
                ('amount_paise', models.BigIntegerField()),
                ('balance_after_paise', models.BigIntegerField()),
                ('gateway_ref', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emergency_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='emergency.emergencyrequest')),
                ('savings_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='savings.savingsaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['savings_account', '-created_at'], name='transaction_savings_0ca943_idx'), models.Index(fields=['user', '-created_at'], name='transaction_user_id_ced08a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('amount_paise__gt', 0)), name='txn_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_ref', ''), _negated=True), fields=('gateway_ref',), name='uniq_gateway_ref'),
        ),
    ]
