# Generated by Django 4.2.30 on 2026-10-06 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('TOP_UP', 'Added from bank'), ('BANK_WITHDRAWAL', 'Withdrawn to bank'), ('TO_SAVINGS', 'Moved into savings'), ('FROM_SAVINGS', 'Released from savings'), ('TO_LOCKER', 'Locked in term locker'), ('FROM_LOCKER', 'Term locker payout'), ('EMERGENCY_RELEASE', 'Emergency release')], max_length=20)),
                ('amount_paise', models.BigIntegerField()),
                ('balance_after_paise', models.BigIntegerField()),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet_transactions',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='wallet_tran_user_id_1da2e3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.CheckConstraint(check=models.Q(('amount_paise__gt', 0)), name='wallet_txn_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.CheckConstraint(check=models.Q(('balance_after_paise__gte', 0)), name='wallet_txn_balance_non_negative'),
        ),
    ]
