# Generated by Django 4.2.30 on 2026-10-06 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_kyc_and_banks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_wallet_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='kind',
            field=models.CharField(choices=[('TOP_UP', 'Added from bank'), ('BANK_WITHDRAWAL', 'Withdrawn to bank'), ('TO_SAVINGS', 'Moved into savings'), ('FROM_SAVINGS', 'Released from savings'), ('TO_LOCKER', 'Locked in term locker (retired)'), ('FROM_LOCKER', 'Term locker payout (retired)'), ('EMERGENCY_RELEASE', 'Emergency release')], max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='razorpay', max_length=20)),
                ('order_id', models.CharField(max_length=64, unique=True)),
                ('payment_id', models.CharField(blank=True, max_length=64)),
                ('amount_paise', models.BigIntegerField()),
                ('status', models.CharField(choices=[('CREATED', 'Awaiting payment'), ('PAID', 'Paid and credited'), ('FAILED', 'Failed')], default='CREATED', max_length=10)),
                ('method', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.linkedbankaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to=settings.AUTH_USER_MODEL)),
                ('wallet_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_order', to='payments.wallettransaction')),
            ],
            options={
                'db_table': 'payment_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentorder',
            constraint=models.CheckConstraint(check=models.Q(('amount_paise__gt', 0)), name='payment_order_amount_positive'),
        ),
    ]
